import type { IssueAnalysis } from "./types.js";

export const REPORT_MARKER = "<!-- issue-proof-report -->";

export function renderAnalysisComment(analysis: IssueAnalysis): string {
  const lines = [
    REPORT_MARKER,
    "## Issue Proof triage",
    "",
    `Classification: \`${analysis.classification}\``,
    `Confidence: \`${analysis.confidence.toFixed(2)}\``,
    "",
  ];

  if (analysis.suggestedLabels.length > 0) {
    lines.push(`Suggested labels: ${analysis.suggestedLabels.map((label) => `\`${label}\``).join(", ")}`, "");
  }

  if (analysis.missingInfo.length > 0) {
    lines.push("Missing information:");
    for (const item of analysis.missingInfo) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  if (analysis.evidence.length > 0) {
    lines.push("Evidence found:");
    for (const item of analysis.evidence) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  if (analysis.warnings.length > 0) {
    lines.push("Warnings:");
    for (const item of analysis.warnings) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  if (analysis.possibleDuplicates.length > 0) {
    lines.push("Possible duplicates:");
    for (const duplicate of analysis.possibleDuplicates) {
      const number = duplicate.number ? `#${duplicate.number} ` : "";
      const link = duplicate.url ? ` - ${duplicate.url}` : "";
      lines.push(`- ${number}${duplicate.title} (${duplicate.similarity.toFixed(2)})${link}`);
    }
    lines.push("");
  }

  lines.push("Suggested next step:", analysis.nextStep, "");
  lines.push("_Generated by Issue Proof. Review before acting._");

  return lines.join("\n");
}
